# 自動ビルドを試みる
name: Build Qt Project

# 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
      runs-on: [macos-latest]
      steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          install-deps: 'true'
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DUSE_QT6='ON'
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release
        
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release
